import Image from 'next/image';
import Image1 from '../public/assets/01.png';
import Image2 from '../public/assets/02.png';
import Image3 from '../public/assets/03.png';
import HeroImage from '../public/assets/hero.png';
import { isMobile } from "react-device-detect";
import React from 'react';
import { Hero } from 'web3uikit';

export default function About() {
    const [hydrated, setHydrated] = React.useState(false);
    React.useEffect(() => {
        setHydrated(true);
    }, []);
    if (!hydrated) {
        // Returns null on first render, so the client and server match
        return null;
    }
    if (isMobile) {
        return (
            <div className="About items-center justify-center">
                <div className="AboutText text-center">
                    <strong className='bigtext'>AI Horror Nights</strong>
                    <br /><br />
                    A collection of images from the AI Horror Nights project. The project is the result of a collaboration between Kodr and the AI Horror Nights team. The project is a collection of 1000 unique images, each one generated by an AI model trained on aliens and horror movie posters. The images are then minted using a KODR.eth Smart Contract and sold on the Ethereum blockchain.
                    <br />
                    <strong>*0.00666E</strong>
                    <br /><br />
                </div>
                <Image src={HeroImage} alt="Hero Image" />
                <Image src={Image1} alt='Image 1' />
                <Image src={Image2} alt='Image 2' />
                <Image src={Image3} alt='Image 3' />
            </div>
        )
    }
    return (
        <div className="About">
            <div className="grid gap-1 grid-cols-2 grid-rows-1 ... text-white" >
                <div className="grid-item mt-4">
                    <Image src={HeroImage} alt="Main Hero Shot" />
                </div>

                <div className="textbox font-din">
                    <strong className='bigtext'>AI Horror Nights</strong>
                    <br /><br />
                    A collection of images from the AI Horror Nights project. The project is the result of a collaboration between Kodr and the AI Horror Nights team. The project is a collection of 1000 unique images, each one generated by an AI model trained on aliens and horror movie posters. The images are then minted using a KODR.eth Smart Contract and sold on the Ethereum blockchain.
                    <br /><br />
                    <strong>*0.00666E</strong>

                </div>
            </div>

            <div className="grid gap-8 grid-flow-row-dense grid-cols-3 grid-rows-1 mt-6 ..." >

                <div className="grid-item place-content-center">
                    <Image src={Image1} alt='Image 1' />
                </div>
                <div className="grid-item place-content-center">
                    <Image src={Image2} alt='Image 2' />
                </div>
                <div className="grid-item place-content-center" >
                    <Image src={Image3} alt='Image 3' />
                </div>
            </div>
        </div>
    )
}

